language: python
python:
  - "3.6"
# command to install dependencies
install: 
- "pip install -r requirements.txt"
- "pip install python-coveralls"
- "pip install coverage"

# command to run tests

script: 
- "python test.py"
- "python test_users_data.py"
- "coverage run test.py test"


after_success: 
- "coveralls"



