language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests

script: "sbt clean coverage test"
after_success: "sbt coveralls"

script: "python test.py"
 